services:
  # Backend FastAPI Service
  - type: web
    name: vesper-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.18
    healthCheckPath: /

  # Frontend Next.js Service
  - type: web
    name: vesper-frontend
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: vesper-backend
          envVarKey: RENDER_EXTERNAL_URL

